Repository hyperlight-dev/hyperlight-wasm, pull requests merged in 2025-05, with the labels that each got.

#51 Remove deislabs references from dockerfile and scripts
  .github/workflows/dep_build_wasm_examples.yml
  src/hyperlight_wasm/scripts/build-wasm-examples.sh
  src/wasmsamples/compile-wasm.bat
  src/wasmsamples/dockerfile
Labels: kind/bugfix

#38 Add FOSSA license validation badge to readme.md
  README.md
Labels: area/documentation, kind/enhancement

#47 fix rustfmt error
  src/hyperlight_wasm/examples/metrics/main.rs
Labels: kind/bugfix

#46 Automatically approve unmodified dependabot requests
  .github/dependabot.yml
  .github/workflows/auto-merge-dependabot.yml
  src/scripts/auto-approve-dependabot.sh
Labels: kind/enhancement, area/infrastructure

#40 Re-use hyperlight dev and add wasm specific tools
  .devcontainer/Dockerfile
Labels: kind/refactor
