Repository hyperlight-dev/hyperlight-wasm, pull requests merged in 2025-07, with the labels that each got.

#84 Bump hyperlight core to 0.7.0
  Cargo.lock
  Cargo.toml
  src/hyperlight_wasm_macro/Cargo.lock
  src/hyperlight_wasm_macro/Cargo.toml
  src/wasm_runtime/Cargo.lock
  src/wasm_runtime/Cargo.toml
Labels: kind/dependencies

#83 Generate vendor.tar in release workflow
  .github/workflows/CreateRelease.yml
  .github/workflows/CreateReleaseBranch.yml
  src/hyperlight_wasm/.gitignore
  src/hyperlight_wasm_macro/.gitignore
Labels: kind/refactor

#90 Fix benchmarks in mshv3
  .github/workflows/Benchmarks.yml
  .github/workflows/CreateRelease.yml
Labels: kind/bugfix

#94 Use CPU in the benchmark artifacts name
  .github/workflows/Benchmarks.yml
  .github/workflows/CreateRelease.yml
  .github/workflows/dep_build_wasm_examples.yml
  .github/workflows/dep_rust.yml
  Justfile
Labels: kind/bugfix

#95 Use bash for archiving benchmarks
  .github/workflows/CreateRelease.yml
Labels: kind/bugfix

#96 Bump crate versions
  Cargo.lock
  src/hyperlight_wasm/Cargo.toml
  src/hyperlight_wasm_aot/Cargo.toml
  src/hyperlight_wasm_macro/Cargo.toml
  src/wasm_runtime/Cargo.toml
Labels: kind/enhancement

#97 Also publish hl-wasm-aot
  .github/workflows/CreateRelease.yml
Labels: kind/bugfix

#100 Fix release workflow
  .github/workflows/CreateRelease.yml
  .github/workflows/CreateReleaseBranch.yml
  Justfile
Labels: kind/bugfix

#101 Update to use the latest wasi sdk
  .devcontainer/Dockerfile
  .github/workflows/CreateDevcontainerImage.yml
  .github/workflows/dep_build_wasm_examples.yml
  src/hyperlight_wasm/scripts/build-wasm-examples.sh
  src/hyperlight_wasm_macro/Cargo.lock
  src/wasm_runtime/src/wasip1.rs
  src/wasmsamples/compile-wasm.bat
  src/wasmsamples/dockerfile
Labels: kind/dependencies

#103 Fix the location of the file extraction
  .devcontainer/Dockerfile
Labels: area/testing, kind/dependencies

#93 Component benchmarks
  .devcontainer/Dockerfile
  .github/workflows/dep_build_wasm_examples.yml
  .github/workflows/dep_rust.yml
  .gitignore
  Justfile
  src/hyperlight_wasm/Cargo.toml
  src/hyperlight_wasm/benches/benchmarks_components.rs
  src/hyperlight_wasm/scripts/build-wasm-examples.sh
  src/wasmsamples/compile-wasm.bat
  src/wasmsamples/components/runcomponent.c
  src/wasmsamples/components/runcomponent.wit
Labels: kind/dependencies

#115 Remove aot acting as wasm
  .github/workflows/dep_build_wasm_examples.yml
  Justfile
  src/hyperlight_wasm/benches/benchmarks.rs
  src/hyperlight_wasm/benches/benchmarks_components.rs
  src/hyperlight_wasm/examples/component_example/main.rs
  src/hyperlight_wasm/examples/helloworld/main.rs
  src/hyperlight_wasm/examples/hostfuncs/main.rs
  src/hyperlight_wasm/examples/metrics/main.rs
  src/hyperlight_wasm/examples/rust_wasm_examples/main.rs
  src/hyperlight_wasm/scripts/build-wasm-examples.sh
  src/hyperlight_wasm/src/sandbox/loaded_wasm_sandbox.rs
  src/hyperlight_wasm/src/sandbox/metrics.rs
  src/hyperlight_wasm/src/sandbox/wasm_sandbox.rs
  src/hyperlight_wasm_macro/Cargo.lock
  src/wasmsamples/compile-wasm.bat
Labels: kind/refactor

#123 Add additional checks on PR before auto approving
  src/scripts/auto-approve-dependabot.sh
Labels: kind/enhancement
